<?php

########################################################################
# Extension Manager/Repository config file for ext: "list"
#
# Auto generated by Extension Builder 2012-04-15
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'list renewed',
	'description' => 'New TYPO3 list module',
	'category' => 'module',
	'author' => 'Daniel Pötzinger',
	'author_email' => 'dev@aoemedia.de',
	'author_company' => 'AOE media',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'extbase' => '1.5',
			'fluid' => '1.5',
			'typo3' => '4.7',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>